[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
solc = "0.8.18"

[fmt]
line_length = 120

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
